### ISSUE TITLE
dateCode is inaccurate

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#23]
The dateCode shows 20082519 after doing `setup` in vivado using v1.0, instead of the firmware date on which it was created.

**Comment by alacrities** [comment]
THe date code is currently yy mm dd hh

**Comment by sebprince** [comment]
With v4_0, when doing `setup` command in vivado, the following is returned `dateCode=21021712`, which is the date and time at which the `setup` command was performed. So the date format is expecting as it is expected.

@alacrities Is that dateCode value taken from the firmware or is that showing the value that will be inserted in the firmware?
If the former, this is a problem and the stored dateCode should be changed so that it corresponds to the date and time at which the firmware was compiled.
If the latter, this is fine and this issue can be closed.

**Comment by alacrities** [comment]
This is fixed in the development branch. Need to verify with the DAQ.

**Comment by sebprince** [comment]
The datecode still shows the current date when doing setup. Is that expected?
